<a href="https://colab.research.google.com/github/vidhipitroda/Extreme-learning-machine/blob/master/ELM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

Fetching the dataset and applying preprocessing steps

In [0]:
#fetching the dataset
dataset = pd.read_csv(r'\\transfusion.csv')

In [0]:
#renaming the dataset
dataset = dataset.rename(columns={"Recency (months)":"Months","Frequency (times)":"Frequency","Monetary (c.c. blood)":"c.c.blood","Time (months)":"Time","whether he/she donated blood in March 2007":"final"})

In [0]:
dataset.head()

Months  Frequency  c.c.blood  Time  final
0       2         50      12500    98      1
1       0         13       3250    28      1
2       1         16       4000    35      1
3       2         20       5000    45      1
4       1         24       6000    77      0

Normalization of dataset

In [0]:
#normalization of dataset
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(dataset)
input_node= pd.DataFrame(x_scaled)
x_train = np.array(input_node)
x_train

array([[0.02702703, 1.        , 1.        , 1.        , 1.        ],
       [0.        , 0.24489796, 0.24489796, 0.27083333, 1.        ],
       [0.01351351, 0.30612245, 0.30612245, 0.34375   , 1.        ],
       ...,
       [0.31081081, 0.04081633, 0.04081633, 0.625     , 0.        ],
       [0.52702703, 0.        , 0.        , 0.38541667, 0.        ],
       [0.97297297, 0.        , 0.        , 0.72916667, 0.        ]])

In [0]:
#arranging the values as per the datatype
X_train = dataset.iloc[:, 0:4].values.astype('float32')
labels = dataset.iloc[:, 4].values.astype('int32')

In [0]:
X_train.shape

(748, 4)

In [0]:
labels.shape

(748,)

In [0]:
labels = labels.reshape(-1,1) #reshaping the labels

performing one hot encoding

In [0]:
#performing one hot encoding in the labels
# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(labels)

# 3. Transform
y = enc.transform(labels).toarray()
y.shape    
y    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

Spliting the dataset into 70:30 ratio

In [0]:
#splitting the dataset into testing and training
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_train, y, test_size=0.3)




Generating random weights and hidden neurons

In [0]:
#Generating random weights and hidden units


Win = np.random.normal(size=[x_train.shape[1], 700])

print('Input Weight shape: {shape}'.format(shape=Win.shape))
Win

Input Weight shape: (4, 700)


array([[ 1.18775709, -0.52558242,  1.86934128, ..., -0.24972353,
        -0.4284569 ,  0.23175202],
       [ 1.37143448, -1.79955095,  0.47594433, ..., -0.30886776,
         0.06869687, -1.13800135],
       [-0.42321844,  1.36261104, -0.1849236 , ..., -1.15256236,
        -0.74908615, -0.3742725 ],
       [ 0.6283884 , -0.01606737, -2.23419491, ...,  0.25448131,
         2.04990744, -0.02372699]])

Applying Relu activation function


In [0]:
#applying Relu activation function
def input_to_hidden(x):
    a = np.maximum(0, x) # ReLU
    return a

Calculating output weight of ELM

In [0]:
#Compute the output weights ELM
X = input_to_hidden(x_train)
s = np.linalg.pinv(X)
wout = np.dot(s,y_train)
wout

array([[ 3.13935331e-02,  1.84814446e-03],
       [-1.90100998e-08,  5.25008121e-07],
       [-4.75254257e-06,  1.31252030e-04],
       [ 8.94797710e-03, -1.06677983e-03]])

calculating the final accuracy

In [0]:
#final prediction method

test_r = input_to_hidden(x_test)
y = np.dot(test_r,wout)
correct = 0
for i in range(y.shape[0]):
    predicted = np.argmax(y[i])
    test = np.argmax(y_test[i])
    correct = correct + (1 if predicted == test else 0)
print('Accuracy: {:f}'.format(correct/y.shape[0] * 100))




Accuracy: 81.333333
